# Site settings
title: redis.cn
email: rjgcs123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  redis
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ghthub.redis.cn" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  geelou

# Build settings
markdown: kramdown
# exclude: ['doc/', 'psd/']
# port: 4001